### PR TITLE
refactor flyout and button creation

### PR DESCRIPTION
**Pull request by jetersen**
I have gone ahead and centralized button creation and flyout button creation to avoid repeated code.
This should also make it easier to do #6 #27 #39

This was first iteration, there could be further cleanup I might have missed.

I am not able to test wormholes as I do not have an engineer. So would appreciate if someone could check that it works.

But since hero paths and mage portal works I assume the wormholes will too.

### CODE REVIEW

**Comment by Justw8** [comment]
While I appreciate the work, this isn't the refactor I am looking for right now.

**Comment by Justw8** [comment]
since you were confused, I updated it with what I did want to do. :)

**Comment by Justw8** [comment]
(see https://github.com/Justw8/TeleportMenu/commit/6929a404030f565072023bf63d8ea31fa5ce6bbd)

**Comment by jetersen** [comment]
@Justw8 I think we could have gotten to the same output but oh well :sweat_smile:

**Pull request closed without merging**
