### PR TITLE
Add text on the dungeon teleports

### PR DESCRIPTION
**Pull request by kayti-wow**
Took a stab at implementing #10 

There is a checkbox to turn it on and off in the options, but it needs a reload after changing the settings.

### CODE REVIEW

**Comment by kayti-wow** [comment]
image

**Comment by Justw8** [comment]
Thanks, I will look at this once I merge in #41 to make sure it's all set. Sorry for the delay!

**Comment by Justw8** [comment]
The seasonal flyout is merged, now, let me know if you want to update this (and perhaps re-work the list slightly to use isCurrentSeason) or if you want me to look at it and fix things up!

**Comment by kayti-wow** [comment]
I'm taking a look now.   I should be able to get something done soon

**Comment by kayti-wow** [comment]
I think this can be merged as it is now and we can come back to refactor out the duplicated code in a different PR?

image

**Comment by Justw8** [comment]
Yep, all good; will be doing a full refactor whenever I find some free time in the future anyways, this'll do for now!

**Pull request merged**
